#!/bin/bash
#SBATCH --job-name=C6
#SBATCH --partition=q36
#SBATCH --mem=10G
#SBATCH --nodes=1
#SBATCH --time=10:00:00
#SBATCH --cpus-per-task=1
#SBATCH --array=1-36%36
#SBATCH --no-requeue

source /home/mkb/.dftb
source /home/mkb/virtualEnvs/python-2.7.13/bin/activate

# Go to the directory where this job was submitted
cd $SLURM_SUBMIT_DIR/../..
python globalOptim_ase3d.py grendel/DFTBrelax2/ $SLURM_ARRAY_TASK_ID
