#!/bin/bash
#SBATCH --job-name=C6
#SBATCH --partition=q16
#SBATCH --mem=50G
#SBATCH --nodes=1
#SBATCH --time=10:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --no-requeue

source /home/mkb/.dftb
source /home/mkb/virtualEnvs/python-2.7.13/bin/activate

# Go to the directory where this job was submitted
cd $SLURM_SUBMIT_DIR/../..
python globalOptim_ase3d.py grendel/DFTBrelax3/
