#!/bin/sh

#PBS -l nodes=8:ppn=12
#PBS -l walltime=12:00:00
#PBS -q q12
#PBS -N HenrikBasinHop


echo "========= Job started  at `date` =========="
# load python
echo "Loading python3.4.3"
module load python/3.4.3
# source virtual environment
echo "Sourcing virtual environment (crystalStructureVenv/bin/activate)"

# python3 /home/hlm/testfolder/createParamListSquaresAndTriangles.py

source /home/hlm/crystalStructures/crystalStructureVenv/bin/activate
mkdir -p $PBS_O_WORKDIR/data/$PBS_JOBID/

cd /scratch/$PBS_JOBID
dispatch -c "/home/hlm/testfolder/master.sh {}" {0..50}

echo "========= Job finished at `date` =========="
